function PhageIntensityvaluessliding = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PHAGEINTENSITYVALUESSLIDING = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  PHAGEINTENSITYVALUESSLIDING = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  PhageIntensityvaluessliding = importfile("C:\Users\lorenzo\Desktop\git\PhD_codes\Pilus_rotation\Phage_Intensity_values_sliding.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Mar-2022 10:18:48

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Slice", "Mean"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
PhageIntensityvaluessliding = readtable(filename, opts);

end